### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by serhiynovos** [Sup3r-Us3r/go-object-detection#1]
Does this sample can work with GPU ? Just wonder how faster it can run if use GPU acceleration

**Comment by Sup3r-Us3r** [comment]
Hello @serhiynovos, I didn't get to test with a GPU because I don't have an NVIDIA graphics card, but I believe that this project I made will be able to run on a GPU, what is important to do is install Tensorflow for the GPU and not CPU, I will forward you some pages that can help you with the process.

https://www.tensorflow.org/install/gpu
https://www.tensorflow.org/install/lang_c

I also recommend that you do not try to run this project via Docker but rather on your real system, since you intend to test with GPU.
